version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      kotlin-plugins:
        patterns:
          - "jvm"
          - "plugin.serialization"
        update-types:
          - minor
          - patch
      gradle-minor-patch:
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "jvm"
          - "plugin.serialization"