name: Chainguard Digest Check

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  chainguard-digests-update:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    name: Chainguard digests update
    uses: navikt/mob-gha-workflows/.github/workflows/chainguard-digestabot.yaml@main
